"""Collect CNmGraphDoc*/CnmGraphDoc* node class names from the CS2 schema dump
and write a ClassName<TAB>RelativePath list to NodeClassLists/cs2_schema_node_classes.txt.

Scans every subdirectory under the schemas root (not just animdoclib) - CS2 keeps
some node classes in separate libraries, e.g. modtools/ for weapon/viewmodel nodes.
Nested type dumps (files named Outer__Nested.h, e.g. CNmGraphDocClipNode__CData.h)
are skipped, since they aren't standalone node classes.
"""

import argparse
import re
import sys
from pathlib import Path

CLASS_PATTERN = re.compile(r"class\s+(C[Nn]mGraphDoc\w*)\b")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

DEFAULT_SCHEMAS_ROOT = Path(r"D:\Work\CS_MODS\CS2\GameTracking-CS2\DumpSource2\schemas")
DEFAULT_OUTPUT = REPO_ROOT / "NodeClassLists" / "cs2_schema_node_classes.txt"


def find_node_classes(schemas_root: Path) -> dict[str, str]:
    results: dict[str, str] = {}

    for header in sorted(schemas_root.rglob("*.h")):
        if "__" in header.stem:
            continue

        try:
            text = header.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        match = CLASS_PATTERN.search(text)
        if match is None:
            continue

        class_name = match.group(1)
        rel_path = header.relative_to(schemas_root).as_posix()
        results[class_name] = rel_path

    return results


def write_output(results: dict[str, str], schemas_root: Path, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    subdirs = sorted({path.split("/", 1)[0] for path in results.values() if "/" in path})

    lines = [
        "# CS2 vnmgraph node/document classes (CNmGraphDoc*/CnmGraphDoc*)",
        f"# Root: {schemas_root}",
        "# Format: ClassName<TAB>RelativePath",
        f"# {len(results)} classes across {len(subdirs)} subdirectories ({', '.join(subdirs)}),"
        " excludes nested types (::CData, ::Data_t etc.)",
        "# Generated by scripts/collect_cs2_node_classes.py - do not edit by hand.",
        "",
    ]

    lines.extend(f"{class_name}\t{results[class_name]}" for class_name in sorted(results))

    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--schemas-root",
        type=Path,
        default=DEFAULT_SCHEMAS_ROOT,
        help=f"Root of the CS2 DumpSource2 schemas directory (default: {DEFAULT_SCHEMAS_ROOT})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output file path for the collected class list (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    if not args.schemas_root.is_dir():
        print(f"Schemas root not found: {args.schemas_root}", file=sys.stderr)
        return 1

    results = find_node_classes(args.schemas_root)
    if not results:
        print("No CNmGraphDoc*/CnmGraphDoc* classes found.", file=sys.stderr)
        return 1

    write_output(results, args.schemas_root, args.output)
    print(f"Wrote {len(results)} classes to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
